name: Dependency Update

on:
  schedule:
    - cron: '0 9 * * 1' # Каждый понедельник в 9:00
  workflow_dispatch: # Ручной запуск

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Update dependencies
        run: |
          pnpm update --latest
          pnpm audit --fix

      - name: Run tests after update
        run: |
          pnpm install
          pnpm run test
          pnpm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated dependency update'
          body: |
            ## Automated Dependency Update
            
            This PR updates all dependencies to their latest versions.
            
            ### Changes
            - Updated all packages to latest versions
            - Fixed security vulnerabilities
            - All tests passed
            
            ### Review
            Please review the changes and merge if everything looks good.
          branch: dependency-update
          delete-branch: true
